import React from 'react';
import {BigText, colors, ease, mono, SceneProps, Stat, TokenRow} from './Shared';

export const DeepSeekScenes:React.FC<SceneProps> = ({cue,progress:p}) => {
  if(cue.visual==='deepseek-compress') return <><BigText accent={colors.red} progress={p} size={72}>先把长文压短</BigText><div style={{position:'absolute',left:160,right:160,top:430,display:'flex',gap:7}}>{Array.from({length:32}).map((_,i)=><div key={i} style={{height:90,flex:1,background:colors.red,translate:`${(i-16)*(1-ease(p))*18}px ${(1-ease(p))*120}px`,scale:`${1-ease(p)*.55} 1`,opacity:.55+(i%4)*.12}}/>)}</div><div style={{position:'absolute',left:690,top:610,width:540,height:100,background:colors.red,color:colors.bg,display:'grid',placeItems:'center',fontFamily:mono,fontSize:40,fontWeight:900}}>COMPRESSED</div></>;
  if(cue.visual==='deepseek-four-one') return <><BigText accent={colors.red} progress={p} size={72}>4 个 Token → 1 个组</BigText>{Array.from({length:4}).map((_,i)=><div key={i} style={{position:'absolute',left:330+i*245+(1-ease(p))*(i-1.5)*160,top:410,width:190,height:150,background:colors.panel,border:`4px solid ${colors.red}`,display:'grid',placeItems:'center',fontFamily:mono,fontSize:44,opacity:1-ease(p)*.4}}>T{i+1}</div>)}<div style={{position:'absolute',right:300,top:420,width:250,height:130,background:colors.red,color:colors.bg,display:'grid',placeItems:'center',fontFamily:mono,fontSize:40,fontWeight:900,opacity:ease(p),scale:`${.7+.3*ease(p)}`}}>GROUP</div></>;
  if(cue.visual==='deepseek-topk') return <><BigText accent={colors.red} progress={p} size={68}>只把相关内容送去细看</BigText><TokenRow count={18} active={18} accent={colors.line}/>{[3,8,14].map((i,k)=><div key={i} style={{position:'absolute',left:170+i*(1580/18),top:400,width:78,height:100,border:`5px solid ${colors.red}`,background:`${colors.red}55`,opacity:ease(p-k*.1),translate:`0 ${-ease(p-k*.1)*90}px`}}/>)}<div style={{position:'absolute',left:690,top:650,width:540,height:90,background:colors.panel,border:`3px solid ${colors.red}`,display:'grid',placeItems:'center',fontFamily:mono,fontSize:30}}>TOP-K DETAIL</div></>;
  if(cue.visual==='deepseek-128') return <><BigText accent={colors.red} progress={p} size={68}>128 份信息，压成 1 份</BigText><div style={{position:'absolute',left:150,top:390,width:1140,display:'grid',gridTemplateColumns:'repeat(16,1fr)',gap:8}}>{Array.from({length:128}).map((_,i)=><span key={i} style={{height:24,background:colors.red,opacity:.25+(i%8)/12,translate:`${(1-ease(p))*(i%16-8)*25}px ${(1-ease(p))*(Math.floor(i/16)-4)*25}px`}}/>)}</div><div style={{position:'absolute',right:270,top:455,width:260,height:180,background:colors.red,color:colors.bg,display:'grid',placeItems:'center',fontFamily:mono,fontSize:54,fontWeight:900,scale:`${.35+.65*ease(p)}`}}>HCA</div></>;
  return <><BigText accent={colors.red} progress={p} size={68}>最近说过的话，单独保留</BigText><div style={{position:'absolute',left:150,right:150,top:400,display:'flex',gap:8}}>{Array.from({length:22}).map((_,i)=><div key={i} style={{height:180,flex:1,background:i>15?colors.red:colors.panel,border:`1px solid ${i>15?colors.red:colors.line}`,opacity:i>15?1:.35}}/>)}</div><div style={{position:'absolute',right:150,top:620,fontFamily:mono,fontSize:34,color:colors.red}}>RECENT WINDOW</div></>;
};

const MemoryPaper:React.FC<{progress:number;erasing?:boolean}> = ({progress,erasing=false}) => <div style={{position:'absolute',right:240,top:260,width:560,height:470,background:'#ece7da',color:colors.bg,padding:42,boxShadow:'0 30px 90px #0009'}}><div style={{fontFamily:mono,fontWeight:900,fontSize:24,color:colors.purple}}>FIXED MEMORY</div>{['人物：林','地点：车站','目标：找到证据','结论：等待确认'].map((line,i)=><div key={line} style={{marginTop:46,fontSize:30,fontWeight:800,opacity:erasing&&i<2?1-ease(progress):ease(progress-i*.12),textDecoration:erasing&&i<2?'line-through':'none'}}>{line}</div>)}</div>;

export const MemAgentScenes:React.FC<SceneProps> = ({cue,progress:p}) => {
  if(cue.visual==='memagent-window') return <><BigText accent={colors.purple} progress={p} size={70}>窗口保持 8K</BigText><div style={{position:'absolute',left:270,right:270,top:440,height:120,border:`4px solid ${colors.purple}`,background:colors.panel}}><div style={{height:'100%',width:'18%',background:colors.purple}}/></div><div style={{position:'absolute',left:270,top:590,fontFamily:mono,fontSize:38}}>8K WINDOW</div><div style={{position:'absolute',right:270,top:590,fontFamily:mono,fontSize:38,color:colors.muted}}>LONG TEXT CONTINUES →</div></>;
  if(cue.visual==='memagent-paper') return <><BigText accent={colors.purple} progress={p} size={70}>给模型一张固定记事纸</BigText><MemoryPaper progress={p}/><div style={{position:'absolute',left:300,top:410,fontSize:120,color:colors.purple,opacity:ease(p)}}>→</div></>;
  if(cue.visual==='memagent-write') return <><div style={{position:'absolute',left:130,top:250,width:806,height:500,display:'flex',gap:14,overflow:'hidden'}}>{Array.from({length:8}).map((_,i)=><div key={i} style={{minWidth:150,height:300,background:colors.panel,borderTop:`5px solid ${colors.purple}`,translate:`${-Math.floor(p*4)*164}px 0`,padding:16,fontFamily:mono}}>CHUNK {i+1}</div>)}</div><MemoryPaper progress={p}/></>;
  if(cue.visual==='memagent-erase') return <><BigText accent={colors.purple} progress={p} size={66}>擦掉旧内容，写入新重点</BigText><MemoryPaper progress={p} erasing/><div style={{position:'absolute',left:300,top:430,width:440,height:130,background:colors.purple,color:colors.bg,display:'grid',placeItems:'center',fontFamily:mono,fontSize:34,fontWeight:900,opacity:ease(p)}}>NEW EVIDENCE →</div></>;
  if(cue.visual==='memagent-rl') return <><BigText accent={colors.purple} progress={p} size={68}>留下什么，由训练学会</BigText>{[['保留',colors.green],['覆盖',colors.red]].map((x,i)=><div key={x[0]} style={{position:'absolute',left:380+i*800,top:410,width:420,height:230,background:colors.panel,border:`4px solid ${x[1]}`,display:'grid',placeItems:'center',fontSize:64,fontWeight:900,color:x[1],scale:`${.75+.25*ease(p-i*.15)}`}}>{x[0]}</div>)}<div style={{position:'absolute',left:835,top:485,fontFamily:mono,fontSize:44,color:colors.muted}}>RL</div></>;
  return <><BigText accent={colors.purple} progress={p} size={66}>小窗口，处理超长文本</BigText><Stat value="8K" label="训练窗口" accent={colors.white} x={330}/><div style={{position:'absolute',left:900,top:450,fontSize:92,color:colors.muted}}>→</div><Stat value="3.5M" label="问答文本" accent={colors.purple} x={1120}/></>;
};
