import React from 'react';
import {BigText, colors, ease, mono, SceneProps, Stat, TokenRow} from './Shared';

const Curve:React.FC<{linear:boolean;progress:number}> = ({linear,progress}) => <div style={{position:'absolute',left:330,top:320,width:1260,height:420,borderLeft:`4px solid ${colors.muted}`,borderBottom:`4px solid ${colors.muted}`}}>{Array.from({length:24}).map((_,i)=>{const x=i/23;const y=linear?x:x*x;return <div key={i} style={{position:'absolute',left:x*1200-8,bottom:y*370-8,width:18,height:18,borderRadius:9,background:linear?colors.yellow:colors.red,opacity:i/23<=progress?1:.12}}/>})}<div style={{position:'absolute',right:0,bottom:-55,fontFamily:mono,color:colors.muted,fontSize:22}}>TEXT LENGTH →</div></div>;

export const MiniMaxScenes:React.FC<SceneProps> = ({cue,progress:p}) => {
  if(cue.visual==='minimax-target') return <><BigText accent={colors.yellow} progress={p} size={74}>最费钱的地方：注意力</BigText><div style={{position:'absolute',left:690,top:360,width:540,height:340,display:'grid',gridTemplateColumns:'repeat(10,1fr)',gap:8}}>{Array.from({length:70}).map((_,i)=><span key={i} style={{background:i<Math.floor(p*70)?colors.yellow:colors.line,opacity:.3+(i%10)/14}}/>)}</div></>;
  if(cue.visual==='minimax-quadratic') return <><BigText accent={colors.red} progress={p} size={72}>越长，计算量涨得越快</BigText><Curve linear={false} progress={p}/></>;
  if(cue.visual==='minimax-linear') return <><BigText accent={colors.yellow} progress={p} size={68}>Lightning Attention<br/>把曲线压平</BigText><Curve linear progress={p}/></>;
  if(cue.visual==='minimax-workers') return <><BigText accent={colors.yellow} progress={p} size={68}>专家分工，机器并行</BigText>{Array.from({length:8}).map((_,i)=><div key={i} style={{position:'absolute',left:230+(i%4)*390,top:360+Math.floor(i/4)*190,width:300,height:130,background:colors.panel,border:`2px solid ${colors.yellow}`,display:'grid',placeItems:'center',fontFamily:mono,fontSize:26,fontWeight:900,opacity:ease(p-i*.07),translate:`0 ${(1-ease(p-i*.07))*50}px`}}>EXPERT {String(i+1).padStart(2,'0')}</div>)}</>;
  return <><BigText accent={colors.yellow} progress={p} size={72}>训练 1M，推理试到 4M</BigText><div style={{position:'absolute',left:180,right:180,top:500,height:16,background:colors.line}}><div style={{width:`${ease(p)*100}%`,height:'100%',background:colors.yellow}}/></div><div style={{position:'absolute',left:170,top:550,fontFamily:mono,fontSize:54}}>1M</div><div style={{position:'absolute',right:160,top:550,fontFamily:mono,fontSize:82,color:colors.yellow,fontWeight:900}}>4M</div></>;
};

const Note:React.FC<{x:number;y:number;accent:string;label:string;opacity?:number}> = ({x,y,accent,label,opacity=1}) => <div style={{position:'absolute',left:x,top:y,width:470,height:330,background:'#f0eadc',color:'#182028',padding:34,rotate:'-2deg',opacity,boxShadow:'0 24px 80px #0008'}}><div style={{fontFamily:mono,fontSize:22,fontWeight:900,color:accent}}>{label}</div>{[0,1,2,3,4].map(i=><div key={i} style={{marginTop:30,height:8,width:`${92-i*8}%`,background:i===1?accent:'#8b8b8355'}}/>)}</div>;

export const KimiScenes:React.FC<SceneProps> = ({cue,progress:p}) => {
  if(cue.visual==='kimi-notes') return <><BigText accent={colors.blue} progress={p} size={70}>边读，边记笔记</BigText><div style={{position:'absolute',left:170,top:400,width:520,height:300,display:'flex',gap:12}}>{Array.from({length:12}).map((_,i)=><div key={i} style={{flex:1,height:100+(i%4)*45,background:i<p*12?colors.blue:colors.line}}/>)}</div><Note x={1110} y={350} accent={colors.blue} label="RUNNING NOTES" opacity={ease(p)}/></>;
  if(cue.visual==='kimi-summary') return <><BigText accent={colors.blue} progress={p} size={68}>多数层，只留一份摘要</BigText>{Array.from({length:10}).map((_,i)=><div key={i} style={{position:'absolute',left:210+i*135,top:360+i%2*70,width:105,height:190,background:colors.panel,borderTop:`5px solid ${colors.blue}`,opacity:1-ease(p)*.75}}/>)}<div style={{position:'absolute',left:650,top:610,width:620,height:110,background:colors.blue,color:colors.bg,display:'grid',placeItems:'center',fontFamily:mono,fontSize:38,fontWeight:900,scale:`${.5+.5*ease(p)}`}}>ONE SUMMARY STATE</div></>;
  if(cue.visual==='kimi-archive') return <><BigText accent={colors.blue} progress={p} size={68}>少数层，负责精确查原文</BigText>{Array.from({length:7}).map((_,i)=><div key={i} style={{position:'absolute',left:220+i*220,top:390,width:170,height:260,background:i===Math.floor(p*7)?colors.blue:colors.panel,border:`2px solid ${colors.blue}`,padding:18,fontFamily:mono,fontSize:18}}>PAGE {i+1}</div>)}<div style={{position:'absolute',left:215+p*1320,top:350,width:190,height:340,border:`6px solid ${colors.yellow}`}}/></>;
  if(cue.visual==='kimi-switch') return <><Note x={250} y={330} accent={colors.blue} label="摘要 / SUMMARY"/><div style={{position:'absolute',left:880,top:470,fontSize:90,color:colors.muted,rotate:`${p*180}deg`}}>↔</div><div style={{position:'absolute',right:250,top:280,width:470,height:430,background:colors.panel,border:`3px solid ${colors.blue}`,padding:36,opacity:ease(p)}}><div style={{fontFamily:mono,color:colors.blue,fontSize:24}}>原文 / SOURCE</div>{Array.from({length:8}).map((_,i)=><div key={i} style={{marginTop:28,height:8,width:`${92-(i%3)*15}%`,background:i===4?colors.yellow:colors.line}}/>)}</div></>;
  return <><BigText accent={colors.blue} progress={p} size={66}>少占显存，也能更快生成</BigText><Stat value="-75%" label="KV Cache" accent={colors.blue} x={330}/><Stat value="6×" label="最高生成速度" accent={colors.yellow} x={1120}/></>;
};
