import React from 'react';
import {interpolate} from 'remotion';
import {BigText, colors, ease, mono, SceneProps, Stat, TokenRow} from './Shared';

const Document:React.FC<{x:number;y:number;h?:number;accent?:string;opacity?:number}> = ({x,y,h=290,accent=colors.green,opacity=1}) => <div style={{position:'absolute',left:x,top:y,width:210,height:h,background:colors.panel,border:`2px solid ${accent}`,padding:22,opacity}}><div style={{fontFamily:mono,color:accent,fontWeight:800}}>DOCUMENT</div>{[0,1,2,3,4].map(i=><div key={i} style={{marginTop:24,width:`${90-i*7}%`,height:8,background:colors.line}}/>)}</div>;

export const OpeningScenes:React.FC<SceneProps> = ({cue,progress:p}) => {
  if(cue.visual==='scale-question') return <><BigText accent={colors.green} progress={p}>1,000,000<br/>TOKEN</BigText><div style={{position:'absolute',left:260,right:260,top:530,height:8,background:colors.line}}><div style={{width:`${ease(p)*100}%`,height:'100%',background:colors.green}}/></div><div style={{position:'absolute',left:250,right:250,top:565,display:'flex',justifyContent:'space-between',fontFamily:mono,fontSize:30,color:colors.muted}}><span>8K</span><span>128K</span><span style={{color:colors.green}}>1M</span></div></>;
  if(cue.visual==='books-stack') return <><BigText accent={colors.white} progress={p} size={74}>一次读完一大摞文字</BigText>{Array.from({length:7}).map((_,i)=><div key={i} style={{position:'absolute',left:420+i*135,top:650-i*44,width:520-i*28,height:54,background:[colors.blue,colors.purple,colors.green][i%3],translate:`${(1-ease(p))*900}px 0`,opacity:ease(p),boxShadow:'0 10px 30px #0008'}}><span style={{fontFamily:mono,color:colors.bg,fontWeight:900,padding:14,display:'block'}}>BOOK {i+1}</span></div>)}</>;
  if(cue.visual==='door-first-step') return <><div style={{position:'absolute',left:670,top:175,width:580,height:630,border:`10px solid ${colors.green}`,background:colors.panel,overflow:'hidden'}}><div style={{position:'absolute',inset:0,background:colors.green,transformOrigin:'left',scale:`${1-ease(p)} 1`}}/><div style={{position:'absolute',right:32,top:290,width:24,height:24,borderRadius:12,background:colors.yellow}}/></div><div style={{position:'absolute',left:760,top:430,fontFamily:mono,fontSize:70,fontWeight:900}}>STEP 01</div></>;
  return <><BigText accent={colors.white} progress={p} size={70}>长文本要过三关</BigText>{[['记得住',colors.blue],['找得准',colors.yellow],['算得动',colors.red]].map((item,i)=><div key={item[0]} style={{position:'absolute',left:180+i*550,top:390,width:460,height:280,background:colors.panel,borderTop:`6px solid ${item[1]}`,opacity:ease(p-i*.12),translate:`0 ${(1-ease(p-i*.12))*70}px`,display:'grid',placeItems:'center',fontSize:58,fontWeight:900,color:item[1]}}>{item[0]}</div>)}</>;
};

export const QwenScenes:React.FC<SceneProps> = ({cue,progress:p}) => {
  if(cue.visual==='qwen-material') return <><BigText accent={colors.green} progress={p} size={76}>先准备足够多的长文本</BigText>{[0,1,2,3].map(i=><Document key={i} x={250+i*365} y={360+(i%2)*45} accent={colors.green} opacity={ease(p-i*.1)}/>)}</>;
  if(cue.visual==='qwen-stitch') return <><div style={{position:'absolute',left:80,right:80,top:180,display:'flex',gap:20}}>{Array.from({length:8}).map((_,i)=><div key={i} style={{height:280,width:190,background:colors.panel,borderTop:`5px solid ${colors.green}`,translate:`${interpolate(ease(p),[0,1],[i%2?-180:180,0])}px 0`,opacity:ease(p)}}><div style={{margin:24,height:8,background:colors.line}}/><div style={{margin:24,height:8,width:'55%',background:colors.line}}/></div>)}</div><div style={{position:'absolute',left:170,right:170,top:590,height:110,background:colors.green,color:colors.bg,fontFamily:mono,fontSize:44,fontWeight:900,display:'grid',placeItems:'center',scale:`${.5+.5*ease(p)}`}}>ONE LONG DOCUMENT</div></>;
  if(cue.visual==='qwen-ruler') return <><BigText accent={colors.green} progress={p} size={78}>窗口一点点拉长</BigText><div style={{position:'absolute',left:170,right:170,top:480,height:12,background:colors.line}}><div style={{height:'100%',width:`${ease(p)*100}%`,background:colors.green}}/></div>{[['128K',170],['256K',580],['512K',990],['1M',1530]].map(([label,x],i)=><div key={String(label)} style={{position:'absolute',left:Number(x),top:430,fontFamily:mono,fontSize:38,color:i<=Math.floor(p*4)?colors.green:colors.muted}}>{label}</div>)}</>;
  if(cue.visual==='qwen-qa') return <><div style={{position:'absolute',left:210,top:230,width:620,height:420,border:`3px solid ${colors.green}`,background:colors.panel,padding:40,translate:`${(1-ease(p))*-240}px 0`}}><div style={{fontSize:42,fontWeight:900}}>长文问题</div><div style={{marginTop:80,fontSize:30,color:colors.muted}}>前文中，作者为什么改变方案？</div></div><div style={{position:'absolute',right:210,top:340,width:620,height:420,border:`3px solid ${colors.yellow}`,background:colors.panel,padding:40,translate:`${(1-ease(p))*240}px 0`}}><div style={{fontSize:42,fontWeight:900,color:colors.yellow}}>长文回答</div><div style={{marginTop:80,fontSize:30,color:colors.muted}}>找到证据，再组织答案。</div></div></>;
  if(cue.visual==='qwen-chunks') return <><BigText accent={colors.green} progress={p} size={72}>分块装入，只算重点</BigText><TokenRow count={18} active={Math.max(1,Math.floor(p*18))} accent={colors.green}/>{[2,7,12,16].map(i=><div key={i} style={{position:'absolute',left:170+i*(1580/18),top:405,width:70,height:90,border:`4px solid ${colors.yellow}`,opacity:ease(p-.35)}}/>)}</>;
  return <><BigText accent={colors.green} progress={p} size={72}>一百万 Token 装入提速</BigText><Stat value="3×" label="起步" accent={colors.white} x={360}/><div style={{position:'absolute',left:870,top:450,fontSize:90,color:colors.muted}}>→</div><Stat value="7×" label="最高" accent={colors.green} x={1120}/></>;
};
