import React from 'react';
import {BigText, colors, ease, mono, SceneProps, Stat} from './Shared';

export const WriterScenes:React.FC<SceneProps> = ({cue,progress:p}) => {
  if(cue.visual==='writer-question') return <><BigText accent={colors.cyan} progress={p} size={70}>能读很长，也要能写很长</BigText><div style={{position:'absolute',left:270,top:410,fontFamily:mono,fontSize:64,color:colors.muted}}>INPUT</div><div style={{position:'absolute',left:660,top:420,width:600,height:90,background:colors.cyan,color:colors.bg,display:'grid',placeItems:'center',fontFamily:mono,fontSize:38,fontWeight:900}}>LONGWRITER</div><div style={{position:'absolute',right:250,top:410,fontFamily:mono,fontSize:64,color:colors.cyan}}>OUTPUT</div></>;
  if(cue.visual==='writer-outline') return <><BigText accent={colors.cyan} progress={p} size={68}>先列章节，再逐章写</BigText>{['总纲','第一章','第二章','第三章','合并'].map((x,i)=><div key={x} style={{position:'absolute',left:230+i*300,top:390+i%2*100,width:250,height:130,background:i===0?colors.cyan:colors.panel,color:i===0?colors.bg:colors.white,border:`3px solid ${colors.cyan}`,display:'grid',placeItems:'center',fontSize:34,fontWeight:900,opacity:ease(p-i*.12),translate:`0 ${(1-ease(p-i*.12))*70}px`}}>{x}</div>)}</>;
  if(cue.visual==='writer-training') return <><BigText accent={colors.cyan} progress={p} size={68}>训练材料也要足够长</BigText><div style={{position:'absolute',left:210,top:390,width:1500,height:180,background:colors.panel}}><div style={{height:'100%',width:`${ease(p)*100}%`,background:colors.cyan}}/></div><div style={{position:'absolute',left:210,top:610,fontFamily:mono,fontSize:42}}>2K WORDS</div><div style={{position:'absolute',right:210,top:610,fontFamily:mono,fontSize:64,color:colors.cyan,fontWeight:900}}>32K WORDS</div></>;
  return <><BigText accent={colors.cyan} progress={p} size={70}>长文输出超过一万词</BigText><div style={{position:'absolute',left:460,right:460,top:390,textAlign:'center',fontFamily:mono,fontSize:190,fontWeight:900,color:colors.cyan}}>{Math.round(10000*ease(p)).toLocaleString()}</div><div style={{position:'absolute',left:600,right:600,top:640,height:12,background:colors.line}}><div style={{height:'100%',width:`${ease(p)*100}%`,background:colors.cyan}}/></div></>;
};

const Lane:React.FC<{label:string;name:string;color:string;y:number;progress:number}> = ({label,name,color,y,progress}) => <div style={{position:'absolute',left:260,right:260,top:y,height:100,background:colors.panel,borderLeft:`7px solid ${color}`,display:'flex',alignItems:'center',justifyContent:'space-between',padding:'0 36px',opacity:ease(progress),translate:`${(1-ease(progress))*100}px 0`}}><span style={{fontSize:34,fontWeight:900}}>{label}</span><span style={{fontFamily:mono,fontSize:26,color}}>{name}</span></div>;

export const SummaryScenes:React.FC<SceneProps> = ({cue,progress:p}) => {
  if(cue.visual==='summary-problems') return <><BigText accent={colors.white} progress={p} size={68}>六条路线，处理三件事</BigText>{[['记忆',colors.blue],['检索',colors.yellow],['成本',colors.red]].map((x,i)=><div key={x[0]} style={{position:'absolute',left:260+i*510,top:400,width:420,height:240,borderTop:`7px solid ${x[1]}`,background:colors.panel,display:'grid',placeItems:'center',fontSize:58,fontWeight:900,color:x[1],opacity:ease(p-i*.14)}}>{x[0]}</div>)}</>;
  if(cue.visual==='summary-qmk') return <><Lane label="补齐长文训练" name="QWEN" color={colors.green} y={300} progress={p}/><Lane label="减少计算和显存" name="MINIMAX · KIMI" color={colors.yellow} y={500} progress={p-.18}/></>;
  if(cue.visual==='summary-dm') return <><Lane label="压缩后再查重点" name="DEEPSEEK" color={colors.red} y={300} progress={p}/><Lane label="边读边更新记忆" name="MEMAGENT" color={colors.purple} y={500} progress={p-.18}/></>;
  if(cue.visual==='summary-writer') return <><BigText accent={colors.cyan} progress={p} size={76}>读得长，也写得长</BigText><div style={{position:'absolute',left:300,right:300,top:430,height:250,background:colors.panel,border:`4px solid ${colors.cyan}`,overflow:'hidden'}}>{Array.from({length:16}).map((_,i)=><div key={i} style={{margin:'12px 30px',height:7,width:`${45+(i%5)*10}%`,background:i<Math.floor(p*16)?colors.cyan:colors.line}}/>)}</div></>;
  return <><BigText accent={colors.green} progress={p} size={74}>一百万上下文<br/>是一整套工程</BigText>{[[colors.green,-420],[colors.yellow,-210],[colors.blue,0],[colors.red,210],[colors.purple,420]].map((x,i)=><div key={i} style={{position:'absolute',left:895+Number(x[1]),top:520,width:130,height:130,borderRadius:65,background:String(x[0]),scale:`${.2+.8*ease(p-i*.1)}`,boxShadow:`0 0 60px ${x[0]}66`}}/>)}<div style={{position:'absolute',left:350,right:350,top:710,height:8,background:colors.line}}><div style={{height:'100%',width:`${ease(p)*100}%`,background:colors.green}}/></div></>;
};
